---
title: "STT 5811 HW02: Categorical Data"
subtitle: PUT YOUR NAME HERE
date: "`r format(Sys.time(), '%A, %B %d, %Y @ %I:%M %p')`"
output:
  pdf_document:
    toc: true
    toc_depth: '2'
---

# Instructions

Do all even-numbered exercises in [**IMS2E Section 4.8**](https://openintro-ims.netlify.app/explore-categorical#sec-chp4-exercises). Use complete sentences and explain your answers for those questions where you are asked to do so.

# Section 4.8 Exercises

## Exercise 2

a. ERASE AND TYPE YOUR ANSWER HERE

b. ERASE AND TYPE YOUR ANSWER HERE

c. ERASE AND TYPE YOUR ANSWER HERE

d. ERASE AND TYPE YOUR ANSWER HERE

e. ERASE AND TYPE YOUR ANSWER HERE

f. ERASE AND TYPE YOUR ANSWER HERE

## Exercise 4

a. ERASE AND TYPE YOUR ANSWER HERE

b. ERASE AND TYPE YOUR ANSWER HERE

## Exercise 6

a. ERASE AND TYPE YOUR ANSWER HERE

b. ERASE AND TYPE YOUR ANSWER HERE

c. ERASE AND TYPE YOUR ANSWER HERE

d. ERASE AND TYPE YOUR ANSWER HERE

## Exercise 8

a. ERASE AND TYPE YOUR ANSWER HERE

b. ERASE AND TYPE YOUR ANSWER HERE

c. ERASE AND TYPE YOUR ANSWER HERE

## Exercise 10

a. ERASE AND TYPE YOUR ANSWER HERE

b. ERASE AND TYPE YOUR ANSWER HERE

c. ERASE AND TYPE YOUR ANSWER HERE

d. ERASE AND TYPE YOUR ANSWER HERE

